"""SQLAlchemy mappings for the payment domain.

Mirrors `model Payment` (and the few `model Order` columns it depends on) from
`prisma/schema.prisma`. Read the rule in `models/base.py` first: **Prisma owns
the DDL.** These classes describe tables that already exist and never create
or alter anything.

`Order` here is a *partial* mirror — only the columns the payment domain needs
to resolve its foreign key and to read the amount a payment should match. It is
not an invitation to grow an order service in the backend; when that happens,
the model grows with it, one column at a time, against the schema.

Why a partial mirror is safe rather than sloppy: SQLAlchemy only requires that
every column it *names* exists with the type it expects. Extra columns in the
real table (all of `Order`'s delivery and notes fields, say) are simply not
selected. The failure mode to avoid is the reverse — declaring a column the
schema doesn't have — which is why a change here must always be preceded by a
change in `schema.prisma`.
"""

from __future__ import annotations

import uuid
from datetime import datetime
from typing import Any

from sqlalchemy import DateTime, ForeignKey, Index, Integer, String, UniqueConstraint, func, text
from sqlalchemy.dialects.postgresql import ENUM as PG_ENUM
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.base import Base

# ─── Postgres enum types ─────────────────────────────────────────────────────
# `create_type=False` everywhere: Prisma created these types, and a second
# `CREATE TYPE` would fail (or, on a fresh database where this ran first, would
# quietly take ownership of DDL that belongs to the schema).
#
# Names are the exact Prisma enum names — Postgres identifiers are
# case-sensitive when quoted, and Prisma quotes them.

PaymentProviderEnum = PG_ENUM(
    "PAYHERO",
    "DARAJA",
    "MANUAL",
    name="PaymentProvider",
    create_type=False,
)
"""Which processor moved the money. `DARAJA` is reserved and unimplemented."""

PaymentMethodEnum = PG_ENUM(
    "MOBILE_MONEY",
    "CARD",
    "BANK_TRANSFER",
    "CASH_ON_DELIVERY",
    name="PaymentMethod",
    create_type=False,
)
"""The channel the customer paid through — not the processor."""

PaymentStatusEnum = PG_ENUM(
    "PENDING",
    "PROCESSING",
    "SUCCESS",
    "FAILED",
    "CANCELLED",
    "REFUNDED",
    name="PaymentStatus",
    create_type=False,
)

OrderStatusEnum = PG_ENUM(
    "PENDING",
    "CONFIRMED",
    "PAID",
    "SHIPPED",
    "DELIVERED",
    "COMPLETED",
    "CANCELLED",
    "REFUNDED",
    name="OrderStatus",
    create_type=False,
)


def _uuid_pk() -> Any:
    """UUID primary key generated by Postgres, matching Prisma's
    `@default(dbgenerated("gen_random_uuid()"))`.

    Server-side, not client-side: two writers generating ids independently is
    how a duplicate key surfaces only under concurrency, and `gen_random_uuid()`
    is core Postgres 13+, so this needs no extension on any provider.
    """
    return mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
        default=uuid.uuid4,
    )


class Order(Base):
    """Partial mirror of `model Order` → `public.orders`."""

    __tablename__ = "orders"

    id: Mapped[uuid.UUID] = _uuid_pk()
    #: Human-facing order number (`MH-…`). Doubles as `Payment.customer_reference`,
    #: which is why the payment domain needs it.
    order_number: Mapped[str] = mapped_column(String, nullable=False)
    buyer_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), nullable=False)
    seller_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), nullable=False)
    status: Mapped[str] = mapped_column(
        OrderStatusEnum, nullable=False, server_default=text("'PENDING'::\"OrderStatus\"")
    )
    subtotal_cents: Mapped[int] = mapped_column(Integer, nullable=False)
    total_cents: Mapped[int] = mapped_column(Integer, nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    #: Prisma's `@updatedAt` is applied by the Prisma client, not by the
    #: database, so there is no trigger to rely on. Any write through this
    #: model has to carry its own refresh — without `onupdate`, an order the
    #: backend touches keeps its creation timestamp forever, which makes
    #: "recently changed orders" queries silently wrong.
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now(), onupdate=func.now()
    )

    __table_args__ = (
        # Named as Prisma generates it, so `prisma migrate diff` sees no drift.
        # Declared here rather than as `unique=True` on the column: both at
        # once describe the *same* constraint twice, and any DDL emitted from
        # that would create two indexes on one column.
        UniqueConstraint("order_number", name="orders_order_number_key"),
    )

    payments: Mapped[list[Payment]] = relationship(
        back_populates="order",
        cascade="all, delete-orphan",
        passive_deletes=True,
    )


class Payment(Base):
    """Mirror of `model Payment` → `public.payments`. Provider-agnostic.

    Column-by-column, this is the Phase 8 generalization: the M-Pesa-specific
    columns (`mpesa_checkout_request_id`, `mpesa_merchant_request_id`,
    `mpesa_receipt_number`, `mpesa_phone_number`, `result_code`, `result_desc`)
    are gone, replaced by `provider` + `provider_transaction_id` +
    `provider_reference` + `payer_reference` + `failure_code`. See the model
    comment in `prisma/schema.prisma` for the full mapping and
    `prisma/migrations/manual_phase8_provider_agnostic_payments.sql` for the
    data migration.
    """

    __tablename__ = "payments"

    id: Mapped[uuid.UUID] = _uuid_pk()
    order_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("orders.id", ondelete="CASCADE"),
        nullable=False,
    )
    provider: Mapped[str] = mapped_column(
        PaymentProviderEnum, nullable=False, server_default=text("'PAYHERO'::\"PaymentProvider\"")
    )
    method: Mapped[str] = mapped_column(PaymentMethodEnum, nullable=False)
    status: Mapped[str] = mapped_column(
        PaymentStatusEnum, nullable=False, server_default=text("'PENDING'::\"PaymentStatus\"")
    )
    #: Integer minor units. Never a float, never a provider-formatted string.
    amount_cents: Mapped[int] = mapped_column(Integer, nullable=False)
    currency: Mapped[str] = mapped_column(String, nullable=False, server_default=text("'KES'"))

    #: The processor's own transaction id. Unique, so a retried callback matches
    #: exactly one row and can be applied idempotently.
    provider_transaction_id: Mapped[str | None] = mapped_column(String, nullable=True)
    #: The settlement/receipt reference a customer can quote to their operator.
    provider_reference: Mapped[str | None] = mapped_column(String, nullable=True)
    #: *Our* reference (the order number), echoed back by the provider. The join
    #: key for a callback that arrives before we've stored a provider id.
    customer_reference: Mapped[str] = mapped_column(String, nullable=False)
    #: Provider-reported payer handle (an MSISDN, a masked PAN). PII: never
    #: logged, and never returned on a public or seller-facing endpoint.
    payer_reference: Mapped[str | None] = mapped_column(String, nullable=True)

    #: Opaque provider-specific detail. Not indexed, not queried. Named
    #: `provider_metadata` in Python because `metadata` is reserved by
    #: SQLAlchemy's declarative base — the *column* is still `metadata`.
    provider_metadata: Mapped[dict[str, Any] | None] = mapped_column("metadata", JSONB, nullable=True)

    failure_code: Mapped[str | None] = mapped_column(String, nullable=True)
    failure_reason: Mapped[str | None] = mapped_column(String, nullable=True)
    #: Verbatim callback body, kept for dispute resolution and re-verification.
    raw_callback_payload: Mapped[dict[str, Any] | None] = mapped_column(JSONB, nullable=True)
    retry_count: Mapped[int] = mapped_column(Integer, nullable=False, server_default=text("0"))
    paid_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    #: Prisma's `@updatedAt` is maintained by the client, not the database, so
    #: there is no server-side trigger to rely on. Any write through this model
    #: must set it explicitly — `onupdate=func.now()` covers SQLAlchemy's own
    #: UPDATEs and is the reason it is declared here.
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
    )

    order: Mapped[Order] = relationship(back_populates="payments", passive_deletes=True)

    __table_args__ = (
        # Names match what Prisma generates, so a `prisma migrate diff` sees no
        # drift between the two descriptions of the same table.
        #
        # These two unique constraints are declared *only* here. The columns
        # carry no inline `unique=True`: the inline flag produces an
        # additional, unnamed constraint, so the same uniqueness would be
        # described twice and emitted as two indexes on one column.
        Index("payments_order_id_idx", "order_id"),
        Index("payments_status_idx", "status"),
        Index("payments_provider_status_idx", "provider", "status"),
        UniqueConstraint("provider_transaction_id", name="payments_provider_transaction_id_key"),
        UniqueConstraint("provider_reference", name="payments_provider_reference_key"),
    )

    # ─── Convenience ────────────────────────────────────────────────────────

    @property
    def is_terminal(self) -> bool:
        """True once the status can no longer change.

        The guard a webhook handler must check *before* applying a transition:
        providers retry callbacks, and a retry against an already-settled
        payment must be a no-op, not a second settlement or a second
        notification.
        """
        return self.status in _TERMINAL_STATUSES

    @property
    def is_settled(self) -> bool:
        return self.status == "SUCCESS"


_TERMINAL_STATUSES = frozenset({"SUCCESS", "FAILED", "CANCELLED", "REFUNDED"})


__all__ = ["Order", "Payment"]
