"""SQLAlchemy mappings for the identity domain.

Mirrors the three tables the backend needs in order to turn an *authenticated*
caller into an *authorized* one: `users`, and the two existence/flag checks that
define MaliHub's roles (`profiles.onboarded`, and whether a `sellers` row
exists). Read the rule in `models/base.py` first: **Prisma owns the DDL.** These
classes describe tables that already exist and never create or alter anything.

Why this mirror exists at all
─────────────────────────────
Neon Managed Better Auth issues a JWT whose `sub` claim is the **provider's**
user id — `neon_auth.user.id` — which is *not* `public.users.id`. MaliHub's own
id is generated by the application and is what every foreign key in the schema
targets, so it deliberately does not change when the identity provider does. The
bridge between the two is `users.auth_user_id`.

That has a consequence this file exists to serve: **the token authenticates, but
it cannot authorize.** It carries no MaliHub role — there is no `app_metadata`
in a Neon Auth JWT, and the `role` claim it does carry is the string
`"authenticated"`, a Postgres/RLS role, not `BUYER`/`SELLER`/`ADMIN`. Reading
that claim as an application role would make every signed-in user identical, or
would promote whoever could set a claim. So the application role is read here,
from Postgres, on every authenticated request. See `core/identity.py`.

`users.id` is mapped **without** a `server_default`, unlike the payment models.
That is not an oversight: Prisma declares it `String @id @db.Uuid` with no
`@default`, because MaliHub generates the value in application code
(`src/services/account-provisioning.ts`). Adding `gen_random_uuid()` here would
claim a default the schema does not have — and `tests/test_models.py`
deliberately does not include `User` in its server-side-PK parametrization for
exactly that reason.

`auth_user_id` is `String` (TEXT), never `UUID`. Neon's documentation shows
`neon_auth.user.id` as `uuid default_random()` while Better Auth's own default
id generator produces 32-character strings, and the evaluation never reached the
live service to settle which one MaliHub will see (see
`docs/neon-auth-poc/REPORT.md` §F). TEXT accepts both, so the mapping is correct
either way and the join is a plain equality on text.
"""

from __future__ import annotations

import uuid
from typing import Any

from sqlalchemy import Boolean, String, UniqueConstraint, text
from sqlalchemy.dialects.postgresql import ENUM as PG_ENUM
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.models.base import Base

#: MaliHub's application role, matching `enum UserRole` in prisma/schema.prisma.
#: `create_type=False`: Prisma created this Postgres type, and a second
#: `CREATE TYPE` would fail — or, on a fresh database where this ran first,
#: would quietly take ownership of DDL that belongs to the schema.
UserRoleEnum = PG_ENUM(
    "BUYER",
    "SELLER",
    "ADMIN",
    "SUPER_ADMIN",
    name="UserRole",
    create_type=False,
)


def _uuid_pk_server_default() -> Any:
    """UUID primary key generated by Postgres — Prisma's
    `@default(dbgenerated("gen_random_uuid()"))`.

    Used for `profiles.id` and `sellers.id`, which Prisma does generate
    server-side. **Not** used for `users.id`, which MaliHub generates itself.
    """
    return mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    )


class User(Base):
    """Partial mirror of `model User` → `public.users`.

    Only the columns identity resolution reads. The twenty-odd relations on
    `User` (products, orders, chats, refunds, …) belong to the Next.js app; the
    backend maps what it needs, when it needs it — see `models/base.py`.
    """

    __tablename__ = "users"

    #: MaliHub's application identity. The target of every foreign key in the
    #: schema, and the value `AuthContext.subject` must end up holding.
    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True)
    #: The authentication provider's id (JWT `sub`). Nullable and unique: rows
    #: provisioned by the previous provider predate the column and keep NULL
    #: until the documented backfill links them. Postgres allows many NULLs in a
    #: unique index, so legacy rows coexist.
    auth_user_id: Mapped[str | None] = mapped_column(String, nullable=True)
    email: Mapped[str] = mapped_column(String, nullable=False)
    phone: Mapped[str | None] = mapped_column(String, nullable=True)
    #: The authoritative application role. Replaces the retired
    #: `app_metadata.role` JWT claim.
    role: Mapped[str] = mapped_column(
        UserRoleEnum, nullable=False, server_default=text("'BUYER'::\"UserRole\"")
    )
    email_verified: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default=text("false"))
    is_active: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default=text("true"))
    #: Read on every authenticated request, which is what makes ban enforcement
    #: real rather than eventual. The Supabase-era verifier could not do this:
    #: it was stateless, so a banned user kept a working token until it expired.
    is_banned: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default=text("false"))

    __table_args__ = (
        # Named as Prisma generates them, so `prisma migrate diff` sees no
        # drift. Declared here rather than as `unique=True` on the column:
        # both at once describe the same constraint twice.
        UniqueConstraint("auth_user_id", name="users_auth_user_id_key"),
        UniqueConstraint("email", name="users_email_key"),
        UniqueConstraint("phone", name="users_phone_key"),
    )


class Profile(Base):
    """Partial mirror of `model Profile` → `public.profiles`.

    Mapped for exactly one column: `onboarded`, the flag that decides whether a
    user is sent to /complete-profile. Its existence also proves the profile row
    was created, which onboarding requires.
    """

    __tablename__ = "profiles"

    id: Mapped[uuid.UUID] = _uuid_pk_server_default()
    user_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), nullable=False)
    onboarded: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default=text("false"))

    __table_args__ = (UniqueConstraint("user_id", name="profiles_user_id_key"),)


class Seller(Base):
    """Partial mirror of `model Seller` → `public.sellers`.

    Mapped for *existence* only: `requireSellerAccess()` in the Next.js app
    treats "has a sellers row" as seller access regardless of `users.role`, and
    the backend must agree with that rule rather than invent its own. No seller
    business columns are read here.
    """

    __tablename__ = "sellers"

    id: Mapped[uuid.UUID] = _uuid_pk_server_default()
    user_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), nullable=False)

    __table_args__ = (UniqueConstraint("user_id", name="sellers_user_id_key"),)


__all__ = ["Profile", "Seller", "User", "UserRoleEnum"]
