import { randomUUID } from "node:crypto";
import type { Prisma, PrismaClient, UserRole } from "@prisma/client";
import { slugify } from "@/utils";
import type { CompleteProfileInput } from "@/lib/validations/auth";

/**
 * Provisioning of the MaliHub application rows (`users` / `profiles`) that an
 * authenticated identity maps onto, plus the onboarding write that
 * /complete-profile performs.
 *
 * ─── The identity model ────────────────────────────────────────────────────
 * MaliHub keeps TWO ids, and this module is the hinge between them
 * (docs/auth/ARCHITECTURE.md §2):
 *
 *   identity.authUserId   the auth provider's id (Neon Auth today)
 *          │              stored in `users.auth_user_id` (TEXT, UNIQUE)
 *          ▼
 *   application user id   MaliHub's own UUID, `users.id`
 *                         generated by MaliHub, referenced by every FK in the
 *                         schema, and NEVER derived from the provider's id
 *
 * Keeping them apart is what makes an identity provider a replaceable
 * dependency: the previous provider's id was used directly as `users.id`, which
 * is why moving off it looked expensive. It is not expensive now, because
 * nothing downstream of `users.id` changes.
 *
 * ─── Why this module takes a store instead of importing Prisma ─────────────
 * The data store is a parameter so this module stays unit-testable with a fake
 * store — it deliberately does not import `@/lib/prisma`, `server-only`, or the
 * auth SDK. It is provider-agnostic by construction: the caller supplies an
 * `AuthIdentity` and gets application rows back.
 *
 * ─── Why provisioning is application-owned ─────────────────────────────────
 * The mirror rows used to be created by a Postgres trigger on the previous
 * provider's own `auth.users` table (`prisma/migrations/manual_auth_trigger.sql`).
 * That trigger only exists inside a provider-hosted database — it cannot fire
 * against an independent Postgres, and Neon Auth's tables live in a separate
 * `neon_auth` schema that MaliHub must not write to. So application code owns
 * provisioning, idempotently, against whatever `DATABASE_URL` points at.
 */

export class AuthServiceError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "AuthServiceError";
  }
}

/** Any handle that can read/write the app rows: `PrismaClient` or a `$transaction` client. */
export type AccountDataStore = Pick<PrismaClient, "user" | "profile" | "seller">;

/** The subset of `PrismaClient` needed to open a transaction. */
export type TransactionalAccountDataStore = Pick<PrismaClient, "$transaction">;

/**
 * Everything the application rows need from an authenticated identity.
 *
 * `authUserId` is the provider's id and is opaque here — it is matched against
 * `users.auth_user_id` and never parsed, formatted, or assumed to be a UUID.
 * `email` is required because `users.email` is a non-null unique column;
 * `fullName` falls back to `""` exactly as the original trigger did.
 */
export type ProvisioningIdentity = {
  authUserId: string;
  email: string;
  phone: string | null;
  emailVerified: boolean;
  fullName: string;
  avatarUrl: string | null;
};

/**
 * Application authorization state, read from MaliHub's own rows.
 *
 * This is the authoritative source for role / onboarding / seller access. It
 * replaced the previous provider's `app_metadata` JWT claims, which could not
 * be reproduced on Neon Auth (no custom Better Auth plugins, no arbitrary
 * claims) and which were only ever a cache of exactly this read.
 */
export type AuthoritativeOnboardingState = {
  onboarded: boolean;
  role: UserRole;
  hasSellerProfile: boolean;
};

/** The full authorization picture the guards in `src/lib/auth` need. */
export type ApplicationAccessRecord = AuthoritativeOnboardingState & {
  id: string;
  email: string;
  phone: string | null;
  isActive: boolean;
  isBanned: boolean;
};

/**
 * Reads the authoritative application state for an application user id.
 *
 * A missing user/profile is an incomplete account, never an onboarded one. The
 * BUYER fallback matches the Prisma default and lets callers repair a partially
 * provisioned identity without manufacturing elevated privileges. Database
 * failures deliberately propagate so callers cannot mistake an unavailable
 * lookup for a completed profile.
 */
export async function getAuthoritativeOnboardingState(
  db: AccountDataStore,
  userId: string
): Promise<AuthoritativeOnboardingState> {
  const user = await db.user.findUnique({
    where: { id: userId },
    select: {
      role: true,
      profile: { select: { onboarded: true } },
      seller: { select: { id: true } },
    },
  });

  return {
    onboarded: user?.profile?.onboarded === true,
    role: user?.role ?? "BUYER",
    hasSellerProfile: Boolean(user?.seller),
  };
}

/**
 * Reads everything the application-level guards authorize against, in one
 * query. Returns `null` when no application row maps to `userId`.
 */
export async function readApplicationAccess(
  db: AccountDataStore,
  userId: string
): Promise<ApplicationAccessRecord | null> {
  const user = await db.user.findUnique({
    where: { id: userId },
    select: {
      id: true,
      email: true,
      phone: true,
      role: true,
      isActive: true,
      isBanned: true,
      profile: { select: { onboarded: true } },
      seller: { select: { id: true } },
    },
  });

  if (!user) return null;

  return {
    id: user.id,
    email: user.email,
    phone: user.phone,
    isActive: user.isActive,
    isBanned: user.isBanned,
    onboarded: user.profile?.onboarded === true,
    role: user.role,
    hasSellerProfile: Boolean(user.seller),
  };
}

/**
 * Controls whether an authenticated identity may claim an application row that
 * was provisioned by the previous provider and is not yet mapped
 * (`auth_user_id IS NULL`), matched on email address.
 *
 * Off by default — see `shouldLinkUnmappedAccountsByEmail()` in
 * `src/lib/auth/config.ts` and docs/auth/MIGRATION.md §4. Existing accounts are
 * NOT migrated automatically by the auth migration itself.
 */
export type ProvisioningOptions = {
  linkUnmappedByEmail?: boolean;
};

type UserRow = {
  id: string;
  email: string;
  authUserId: string | null;
  role: UserRole;
  isActive: boolean;
  isBanned: boolean;
  phone: string | null;
};

/**
 * Resolves the application user id an auth identity maps to, WITHOUT creating
 * anything. Returns `null` when no row carries that `auth_user_id`.
 *
 * This is the READ half of the mapping; {@link resolveApplicationUserId} is the
 * WRITE half, and keeping them apart is deliberate. The guards in
 * `src/lib/auth/session.ts` run on essentially every request — including public
 * marketing pages that only want to know who is signed in — so a guard that
 * provisioned would put two writes on the hottest path in the application to
 * answer a question that is usually "no rows yet". Provisioning instead stays
 * explicit at the three points where an identity is actually established:
 * sign-up, sign-in, and the /complete-profile transaction.
 *
 * An unmapped identity is therefore a normal, expected result here, not an
 * error: `requireUser()` sends it to /complete-profile, which provisions.
 */
export async function findMappedApplicationUserId(
  db: AccountDataStore,
  authUserId: string
): Promise<string | null> {
  if (!authUserId) return null;

  const mapped = (await db.user.findUnique({
    where: { authUserId },
    select: { id: true },
  })) as { id: string } | null;

  return mapped?.id ?? null;
}

/**
 * Maps an auth-provider identity onto a MaliHub application user id, creating
 * the `users`/`profiles` rows when this identity has never been seen.
 *
 * Idempotent and safe to call on every session establishment: an existing row
 * is left alone apart from `email`/`emailVerified`, and phone/role/name edits
 * the user made are never overwritten.
 *
 * ─── The email-collision rule ──────────────────────────────────────────────
 * `users.email` is UNIQUE, so a brand-new identity whose email already belongs
 * to an application row cannot simply be inserted. Two cases, handled
 * differently on purpose:
 *
 *  1. The row is unmapped (`auth_user_id IS NULL`) and linking is enabled —
 *     this is a legacy account, so it is CLAIMED for the new identity. This is
 *     the mechanism by which an existing account eventually maps to Neon Auth.
 *  2. Otherwise — the row belongs to somebody. Throwing `AuthServiceError` with
 *     copy the caller can show is correct; silently reusing or overwriting the
 *     row would be an account-takeover path.
 *
 * @returns the MaliHub application user id (`users.id`).
 */
export async function resolveApplicationUserId(
  db: AccountDataStore,
  identity: ProvisioningIdentity,
  options: ProvisioningOptions = {}
): Promise<UserRow> {
  if (!identity.authUserId) {
    throw new AuthServiceError(
      "Your sign-in didn't return an account reference. Please try again."
    );
  }
  if (!identity.email) {
    throw new AuthServiceError(
      "Your MaliHub account has no email address on file. Please contact support."
    );
  }

  const mapped = (await db.user.findUnique({
    where: { authUserId: identity.authUserId },
    select: {
      id: true,
      email: true,
      authUserId: true,
      role: true,
      isActive: true,
      isBanned: true,
      phone: true,
    },
  })) as UserRow | null;

  if (mapped) return mapped;

  const byEmail = (await db.user.findFirst({
    where: { email: identity.email },
    select: {
      id: true,
      email: true,
      authUserId: true,
      role: true,
      isActive: true,
      isBanned: true,
      phone: true,
    },
  })) as UserRow | null;

  if (byEmail) {
    if (byEmail.authUserId === null && options.linkUnmappedByEmail) {
      // Claim a legacy account for this identity. Only ever fills an empty
      // mapping — it never moves a row that already belongs to another
      // provider identity, and it changes nothing else about the account.
      await db.user.update({
        where: { id: byEmail.id },
        data: { authUserId: identity.authUserId },
      });
      return { ...byEmail, authUserId: identity.authUserId };
    }

    throw new AuthServiceError(
      byEmail.authUserId === null
        ? "That email is already linked to a MaliHub account that hasn't been moved to the new sign-in system yet. Please contact support."
        : "An account with that email already exists. Try signing in instead."
    );
  }

  const created = (await db.user.create({
    data: {
      // MaliHub generates its own application id. It is deliberately NOT the
      // provider's id: `users.id` is the target of every foreign key in this
      // schema, so tying it to an external system would make the next provider
      // change a destructive migration.
      id: randomUUID(),
      authUserId: identity.authUserId,
      email: identity.email,
      phone: identity.phone,
      emailVerified: identity.emailVerified,
    },
    select: {
      id: true,
      email: true,
      authUserId: true,
      role: true,
      isActive: true,
      isBanned: true,
      phone: true,
    },
  })) as UserRow;

  return created;
}

/**
 * Idempotently makes sure the `users` and `profiles` rows for an authenticated
 * identity exist, and returns the application user id they belong to.
 *
 * `undefined` means "leave as-is" in Prisma, so provisioning may confirm an
 * email address but must never un-confirm one, and never touches phone or role.
 */
export async function ensureUserProvisioned(
  db: AccountDataStore,
  identity: ProvisioningIdentity,
  options: ProvisioningOptions = {}
): Promise<string> {
  const user = await resolveApplicationUserId(db, identity, options);

  await db.user.update({
    where: { id: user.id },
    data: {
      email: identity.email,
      emailVerified: identity.emailVerified || undefined,
    },
  });

  await db.profile.upsert({
    where: { userId: user.id },
    create: {
      userId: user.id,
      fullName: identity.fullName,
      avatarUrl: identity.avatarUrl,
    },
    update: {},
  });

  return user.id;
}

export type CompletedProfileRole = "BUYER" | "SELLER";

/**
 * The whole /complete-profile write, in one transaction:
 *  1. resolve (and if necessary provision) the application rows — this is what
 *     makes a first-ever save work, and it removes the `P2025` "record to
 *     update not found" failure a freshly initialized database used to produce,
 *  2. claim the phone number + set the role on the user,
 *  3. finish the profile (name, county, avatar, onboarded = true),
 *  4. create a starter Seller row when they opted into selling.
 *
 * Throws `AuthServiceError` for conditions the user can fix (phone already
 * claimed, missing email); anything else propagates to the caller, which is
 * responsible for logging it rather than flattening it into generic copy.
 *
 * @returns the application user id alongside the role decision, so the caller
 *          can re-read authoritative state after commit.
 */
export async function saveCompletedProfile(
  db: TransactionalAccountDataStore,
  identity: ProvisioningIdentity,
  input: CompleteProfileInput,
  options: ProvisioningOptions = {}
): Promise<{ userId: string; role: CompletedProfileRole; wantsToSell: boolean }> {
  const wantsToSell = input.accountIntent === "SELLER" || input.accountIntent === "BOTH";
  const role: CompletedProfileRole = wantsToSell ? "SELLER" : "BUYER";

  const userId = await db.$transaction(async (tx: Prisma.TransactionClient) => {
    const resolvedId = await ensureUserProvisioned(tx, identity, options);

    // Phone numbers are unique — surface a friendly conflict instead of a
    // raw Postgres constraint error if someone else already claimed it.
    const existingPhone = await tx.user.findFirst({
      where: { phone: input.phone, NOT: { id: resolvedId } },
      select: { id: true },
    });
    if (existingPhone) {
      throw new AuthServiceError(
        "That phone number is already linked to another MaliHub account."
      );
    }

    await tx.user.update({
      where: { id: resolvedId },
      data: { phone: input.phone, role },
    });

    await tx.profile.update({
      where: { userId: resolvedId },
      data: {
        fullName: input.fullName,
        county: input.county,
        avatarUrl: input.avatarUrl || null,
        onboarded: true,
      },
    });

    if (wantsToSell) {
      const existingSeller = await tx.seller.findUnique({ where: { userId: resolvedId } });
      if (!existingSeller) {
        await tx.seller.create({
          data: {
            userId: resolvedId,
            businessName: input.fullName,
            slug: slugify(input.fullName),
            county: input.county,
          },
        });
      }
    }

    return resolvedId;
  });

  return { userId, role, wantsToSell };
}
