/**
 * This file is meant to be generated by the Supabase CLI, not hand-written —
 * hand-rolled types here would drift from the real schema the moment a
 * migration runs. Generate/refresh it with:
 *
 *   npx supabase login
 *   npx supabase link --project-ref <your-project-ref>
 *   npx supabase gen types typescript --linked > src/types/supabase.ts
 *
 * Until the first run, export a minimal shape so `createClient<Database>()`
 * in src/lib/supabase/{client,server}.ts still type-checks.
 */
export type Database = {
  public: {
    Tables: Record<string, { Row: Record<string, unknown> }>;
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
};
