"""Authentication: verify tokens the identity provider signed. Nothing else.

**Neon Managed Better Auth is MaliHub's identity provider.** This module
contains no password handling, no user table, no signup, no login, no session
store, and no way to mint a token. It takes a JWT the auth service already
signed and answers one question: *is this a valid, unexpired token for a real
user?*

That boundary is the reason the backend can exist without becoming a second
authentication system — the failure mode where two services each own half of
"who is this user" and drift apart. Login/signup stay in the Next.js app
(`src/lib/auth/*`, `src/app/(auth)/*`); the frontend forwards the access token
it already holds as `Authorization: Bearer <token>`.

**A valid token is authentication, not authorization.** Three properties of
Neon Auth's JWTs make that distinction load-bearing rather than philosophical:

* `sub` is the **provider's** user id (`neon_auth.user.id`), *not*
  `public.users.id`. MaliHub's own id is generated by the application and is
  what every foreign key in the schema targets, so it deliberately does not
  change when the identity provider does. The bridge is `users.auth_user_id`,
  and crossing it is a database read — see `core/identity.py`. A backend that
  used `sub` as `users.id` would not fail loudly: it would verify tokens
  successfully and then find nothing, or find someone else's rows.
* There is **no `app_metadata`** claim. The retired implementation mirrored
  MaliHub's authoritative state into that claim so middleware could read role
  and onboarding without a query. The cache could lag the database, and a
  stale `onboarded` is what produced the /dashboard ↔ /complete-profile
  redirect loop this repository fixed twice. Neon Auth accepts no custom
  claims, so the cache is gone rather than reimplemented — `role`,
  `is_onboarded` and `has_seller_profile` are read from Postgres.
* The `role` claim a Neon Auth JWT *does* carry is the string `"authenticated"`
  — a Postgres/RLS role, not MaliHub's application role. Reading it as an app
  role makes every logged-in user identical. It is ignored here, deliberately
  and with a test asserting that a token claiming `"role": "SUPER_ADMIN"` does
  not produce a staff context.

Because resolution is a database read, this backend can do what the stateless
Supabase-era verifier could not: **enforce bans and deactivations immediately**
rather than at token expiry. The cost is one indexed lookup per authenticated
request, which is the price of an answer that cannot go stale.

What is *not* implemented here, deliberately:

* **Token revocation beyond expiry.** A stolen token stays cryptographically
  valid until `exp`. Ban enforcement above covers the account-level case;
  per-token revocation needs a denylist in Redis and is a later phase.
* **Refresh.** Refresh tokens are for the frontend's auth client, never for
  this API. A 401 here means "get a fresh token and retry".

Rollback: `SupabaseJwtVerifier` and the `SUPABASE_*` settings are retained
unmodified and are selected only by `AUTH_PROVIDER=supabase-legacy`, so
reverting is a configuration change rather than a revert of this service
(`docs/auth/MIGRATION.md` §9). Exactly one provider is ever active — a backend
that verified both would honour a stale Supabase token for as long as it
remained unexpired after the cutover.
"""

from __future__ import annotations

import time
from collections.abc import Iterable
from dataclasses import dataclass, field, replace
from typing import Any, Protocol, runtime_checkable

from fastapi import Depends, Request

from app.core.config import Settings, get_settings
from app.core.errors import ForbiddenError, ServiceUnavailableError, UnauthorizedError
from app.core.identity import ApplicationIdentity, IdentityResolver, get_identity_resolver
from app.core.logging import get_logger

logger = get_logger(__name__)

#: Postgres roles that appear in a Supabase JWT's `role` claim. `service_role`
#: must never be accepted as a user token — see the module docstring.
SUPABASE_POSTGRES_ROLES = frozenset({"anon", "authenticated", "service_role"})

#: Application roles, matching the `UserRole` enum in prisma/schema.prisma.
APP_ROLES = frozenset({"BUYER", "SELLER", "ADMIN", "SUPER_ADMIN"})

STAFF_ROLES = frozenset({"ADMIN", "SUPER_ADMIN"})


@dataclass(frozen=True, slots=True)
class AuthContext:
    """Who a verified request belongs to, as far as this backend needs to know.

    Frozen and slot-backed: an identity object that can be mutated mid-request
    by a handler is an authorization bug waiting to happen.
    """

    #: The **provider's** user id — the JWT `sub` claim (`neon_auth.user.id`).
    #: Not `public.users.id`. Recorded on every context because conflating the
    #: two is the single most damaging mistake this migration can produce: it
    #: verifies cleanly and then queries the wrong id.
    auth_user_id: str
    #: MaliHub's application user id (`public.users.id`), resolved through
    #: `users.auth_user_id`. `None` until identity resolution runs — see
    #: `core/identity.py`. Handlers must use *this*, never `auth_user_id`.
    subject: str | None = None
    email: str | None = None
    phone: str | None = None
    #: Application role, read from `users.role` in Postgres. There is no
    #: `app_metadata.role` claim any more, and the JWT's own `role` claim is the
    #: Postgres role `"authenticated"` — ignored for authorization.
    role: str = "BUYER"
    #: `profiles.onboarded`. Read, not cached: a stale value here is what
    #: produced the /dashboard ↔ /complete-profile redirect loop.
    is_onboarded: bool = False
    #: Whether a `sellers` row exists. Not derived from `role`, because
    #: `requireSellerAccess()` in the Next.js app accepts either and the two
    #: services must not disagree about who is a seller.
    has_seller_profile: bool = False
    email_confirmed: bool = False
    #: `users.is_banned` / `users.is_active`, read per request. Enforcing these
    #: here is new: the stateless Supabase-era verifier could not, so a banned
    #: user kept a working token until it expired.
    is_banned: bool = False
    is_active: bool = True
    #: The provider's `jti`, if present. The handle for a future revocation
    #: denylist.
    token_id: str | None = None
    issued_at: int | None = None
    expires_at: int | None = None
    #: Raw claims, for the rare handler that needs something not modelled here.
    #: Read-only by convention; nothing should branch on this when a typed
    #: field exists.
    claims: dict[str, Any] = field(default_factory=dict)

    @property
    def is_mapped(self) -> bool:
        """Whether this identity resolved to a MaliHub account.

        An authenticated-but-unmapped caller is a real state during the cutover
        window (a Neon Auth user whose `users` row was never provisioned), so it
        gets a name rather than being expressed as `subject is None` at fourteen
        call sites.
        """
        return self.subject is not None

    @property
    def is_staff(self) -> bool:
        return self.role in STAFF_ROLES

    @property
    def is_authenticated(self) -> bool:
        return True


@runtime_checkable
class TokenVerifier(Protocol):
    """The seam between "a request arrived" and "we know who sent it".

    Anything implementing this can back the API's auth dependency — Supabase
    JWTs today, a different issuer later, a test double in the suite. Keeping
    it a Protocol (not a base class) means the implementations don't have to
    share an inheritance tree they have nothing in common with.
    """

    async def verify(self, token: str) -> AuthContext:
        """Return an `AuthContext` or raise `UnauthorizedError`. Never None."""
        ...

    @property
    def is_configured(self) -> bool:
        """False means every authenticated route will 503, not silently pass."""
        ...


class UnconfiguredVerifier:
    """Fails closed. Used when the selected provider cannot verify tokens.

    This class exists so that a missing `NEON_AUTH_BASE_URL` produces a loud
    503 rather than an anonymous request that some downstream handler forgets
    to check. Fail-open authentication is the one default that is never
    acceptable.

    It names the *selected* provider's variables in the error, because "token
    verification is not configured" sends whoever is deploying down the Supabase
    path when the provider is Neon — and the two need different values.
    """

    is_configured = False

    def __init__(self, settings: Settings | None = None) -> None:
        self._settings = settings

    @property
    def provider(self) -> str:
        return self._settings.auth_provider if self._settings is not None else "neon"

    async def verify(self, token: str) -> AuthContext:
        logger.error(
            "auth_not_configured",
            extra={
                "event": "auth_not_configured",
                "provider": self.provider,
                "detail": "A request presented a bearer token but verification is unconfigured.",
            },
        )
        hint = (
            self._settings.describe_missing_auth_configuration()
            if self._settings is not None
            else "Set NEON_AUTH_BASE_URL on the backend."
        )
        raise ServiceUnavailableError(f"Authentication is not configured on this service. {hint}")


class SupabaseJwtVerifier:
    """Verify Supabase-issued JWTs.

    Supports both signing configurations Supabase ships:

    * **HS256 with the project's JWT secret** — the default for projects on the
      legacy shared secret. Set `SUPABASE_JWT_SECRET`.
    * **Asymmetric (RS256/ES256) via JWKS** — newer Supabase projects sign with
      a rotating key pair published at
      `{SUPABASE_URL}/auth/v1/.well-known/jwks.json`. Set
      `SUPABASE_JWT_ALGORITHMS=RS256` and install the `jwks` extra
      (`pip install '.[jwks]'`) for `cryptography`.

    The algorithm set is *pinned from configuration*, never read from the
    token's own header. That is what prevents the two classic JWT attacks:
    `alg: none`, and algorithm confusion (re-signing an RS256 token with the
    public key as an HMAC secret). PyJWT enforces the pin for us, but only
    because we hand it an explicit allow-list.
    """

    def __init__(self, settings: Settings | None = None) -> None:
        self._settings = settings or get_settings()
        self._jwks_client: Any | None = None
        self._jwks_checked = False
        self._algorithms = tuple(algorithm.upper() for algorithm in self._settings.supabase_jwt_algorithms)
        self._mode = self._settings.jwt_verification_mode

    @property
    def is_configured(self) -> bool:
        return self._mode != "unconfigured"

    @property
    def mode(self) -> str:
        return self._mode

    async def verify(self, token: str) -> AuthContext:
        if not self.is_configured:
            # Shouldn't happen (the factory returns UnconfiguredVerifier), but
            # belt-and-braces: never fall through to a decode with no key.
            raise ServiceUnavailableError("Authentication is not configured on this service.")

        if not token or not isinstance(token, str):
            raise UnauthorizedError("Authentication required.")

        claims = self._decode(token)
        return self._to_context(claims)

    def _decode(self, token: str) -> dict[str, Any]:
        import jwt
        from jwt import PyJWTError

        settings = self._settings
        options = {
            "verify_signature": True,
            "verify_exp": True,
            "verify_nbf": True,
            "verify_iat": True,
            "verify_aud": bool(settings.supabase_jwt_audience),
            "verify_iss": bool(settings.supabase_jwt_issuer),
            # A JWT with no subject cannot identify a user; refuse it rather
            # than produce an AuthContext with an empty id.
            "require": ["exp", "sub"],
        }
        decode_kwargs: dict[str, Any] = {
            "algorithms": list(self._algorithms),
            "options": options,
            "leeway": settings.jwt_leeway_seconds,
        }
        if settings.supabase_jwt_audience:
            decode_kwargs["audience"] = settings.supabase_jwt_audience
        if settings.supabase_jwt_issuer:
            decode_kwargs["issuer"] = settings.supabase_jwt_issuer

        try:
            if self._mode == "jwks":
                signing_key = self._jwks_signing_key(token)
                return jwt.decode(token, signing_key, **decode_kwargs)
            secret = settings.supabase_jwt_secret
            if secret is None:
                # Unreachable by construction: `jwt_verification_mode` only
                # reports "hs256" when a secret is present. Checked rather than
                # asserted because the alternative under `python -O` is an
                # AttributeError inside token verification — and failing open
                # there is not an option, so this has to fail closed and loud.
                raise ServiceUnavailableError(
                    "Token verification is misconfigured on this server.",
                    details={"reason": "hs256_mode_without_secret"},
                )
            return jwt.decode(token, secret.get_secret_value(), **decode_kwargs)
        except PyJWTError as exc:
            # The exception *type* is logged, never the token and never the
            # exception message for signature failures: PyJWT's messages are
            # specific enough ("signature mismatch" vs "expired") that
            # reflecting them to a caller turns this endpoint into an oracle for
            # iterating on a forgery. The client gets one generic 401.
            logger.info(
                "auth_token_rejected",
                extra={
                    "event": "auth_token_rejected",
                    "reason": type(exc).__name__,
                    "mode": self._mode,
                },
            )
            raise UnauthorizedError("Authentication required.") from exc

    def _jwks_signing_key(self, token: str) -> Any:
        """Fetch (and cache) the JWKS signing key for this token's `kid`."""
        if self._jwks_client is None:
            try:
                from jwt import PyJWKClient
            except ImportError as exc:  # pragma: no cover - depends on extras
                raise ServiceUnavailableError(
                    "JWKS-based token verification needs the 'jwks' extra. "
                    "Install it with: pip install '.[jwks]' (or set "
                    "SUPABASE_JWT_SECRET to use HS256 verification instead)."
                ) from exc
            if not self._settings.supabase_jwks_url:
                raise ServiceUnavailableError("SUPABASE_JWKS_URL is not configured.")
            # PyJWKClient caches the JWKS document in-process and refetches on
            # an unknown `kid` or once `lifespan` elapses, which matches
            # Supabase's key-rotation behaviour. `lifespan=300` bounds how long
            # a rotated-out key stays usable; `timeout` bounds how long a hung
            # JWKS endpoint can stall a request.
            self._jwks_client = PyJWKClient(
                self._settings.supabase_jwks_url,
                cache_keys=True,
                cache_jwk_set=True,
                lifespan=300,
                timeout=10,
            )
        try:
            return self._jwks_client.get_signing_key_from_jwt(token)
        except Exception as exc:
            if not self._jwks_checked:
                logger.warning(
                    "auth_jwks_fetch_failed",
                    extra={"event": "auth_jwks_fetch_failed", "error_type": type(exc).__name__},
                )
                self._jwks_checked = True
            raise UnauthorizedError("Authentication required.") from exc

    def _to_context(self, claims: dict[str, Any]) -> AuthContext:
        subject = claims.get("sub")
        if not isinstance(subject, str) or not subject:
            raise UnauthorizedError("Authentication required.")

        postgres_role = claims.get("role")
        if postgres_role == "service_role":
            # See module docstring. Logged as a warning because it is either a
            # misconfigured client or someone probing with a leaked key — both
            # worth seeing — but the token itself is never logged.
            logger.warning(
                "auth_service_role_token_rejected",
                extra={
                    "event": "auth_service_role_token_rejected",
                    "detail": "A service_role JWT was presented to the API as a user token.",
                },
            )
            raise ForbiddenError("This credential cannot be used to access the API.")

        app_metadata = claims.get("app_metadata") or {}
        if not isinstance(app_metadata, dict):
            app_metadata = {}
        user_metadata = claims.get("user_metadata") or {}
        if not isinstance(user_metadata, dict):
            user_metadata = {}

        role = str(app_metadata.get("role") or "BUYER").upper()
        if role not in APP_ROLES:
            # An unrecognised role is treated as the least-privileged one rather
            # than rejected: the user is genuinely authenticated, and refusing
            # the request outright would turn a data-entry mistake in
            # app_metadata into a total lockout.
            logger.warning(
                "auth_unknown_role",
                extra={"event": "auth_unknown_role", "role": role, "fallback": "BUYER"},
            )
            role = "BUYER"

        email = claims.get("email")
        if not isinstance(email, str) and isinstance(user_metadata.get("email"), str):
            email = user_metadata["email"]
        phone = claims.get("phone")
        if not isinstance(phone, str):
            phone = user_metadata.get("phone") if isinstance(user_metadata.get("phone"), str) else None

        return AuthContext(
            # Legacy provider: its user id *was* `public.users.id` — the two
            # shared a primary key, so no mapping lookup is needed and the
            # claim-derived role below is the rollback path's behaviour, kept
            # byte-for-byte. That equivalence is precisely what the Neon
            # migration removed; see the module docstring.
            auth_user_id=subject,
            subject=subject,
            email=email.lower() if isinstance(email, str) else None,
            phone=phone,
            role=role,
            is_onboarded=app_metadata.get("onboarded") is True,
            has_seller_profile=app_metadata.get("has_seller_profile") is True,
            email_confirmed=bool(claims.get("email_confirmed") or claims.get("email_verified")),
            token_id=claims.get("jti") if isinstance(claims.get("jti"), str) else None,
            issued_at=_as_int(claims.get("iat")),
            expires_at=_as_int(claims.get("exp")),
            claims=claims,
        )


def _as_int(value: Any) -> int | None:
    if isinstance(value, bool):
        return None
    if isinstance(value, int):
        return value
    if isinstance(value, float):
        return int(value)
    if isinstance(value, str) and value.isdigit():
        return int(value)
    return None


class NeonAuthJwtVerifier:
    """Verify Neon Managed Better Auth JWTs, then resolve the MaliHub account.

    Two stages, and the second is what makes the first useful:

    1. **Cryptographic** — signature against the service's published JWKS,
       `exp`/`nbf`/`iat`, `iss`, and a non-empty `sub`. This proves the token
       came from the auth service and has not expired. It proves nothing about
       MaliHub.
    2. **Identity resolution** — `sub` is the provider's id, so it is looked up
       in `users.auth_user_id` to obtain `users.id` and the authoritative role,
       onboarding and seller state (`core/identity.py`).

    Verification is **JWKS-only**. The service publishes public keys and there
    is no shared secret, so no HMAC algorithm is accepted; `Settings` refuses
    one at configuration time rather than this class silently ignoring it. The
    algorithm set is pinned from configuration and never read from the token's
    own header, which is what prevents `alg: none` and algorithm confusion.

    JWKS failures answer **503, not 401**. A key-fetch outage and a forged token
    both arrive as an exception from the JWKS client, and they are hard to tell
    apart — so the choice is which mistake is worse. Reporting an outage as an
    invalid token tells every signed-in client to discard a perfectly good
    credential and re-authenticate, which loops: they sign in, get a fresh
    token, and are rejected again while the outage lasts. Reporting a bad token
    as an outage leaks nothing (the token is still refused) and costs a wrong
    status code. Both fail closed; only one causes a login loop.
    """

    def __init__(
        self,
        settings: Settings | None = None,
        *,
        resolver: IdentityResolver | None = None,
        jwks_client: Any | None = None,
    ) -> None:
        self._settings = settings or get_settings()
        #: Injected in tests. `None` means "build the real PyJWKClient lazily",
        #: so constructing a verifier never performs I/O.
        self._resolver = resolver
        self._jwks_client: Any | None = jwks_client
        self._jwks_checked = False
        self._algorithms = tuple(a.upper() for a in self._settings.neon_auth_jwt_algorithms)
        self._mode = self._settings.neon_jwt_verification_mode

    @property
    def is_configured(self) -> bool:
        return self._mode == "jwks"

    @property
    def mode(self) -> str:
        return self._mode

    @property
    def provider(self) -> str:
        return "neon"

    async def verify(self, token: str) -> AuthContext:
        if not self.is_configured:
            # Belt-and-braces: the factory returns UnconfiguredVerifier, but a
            # verifier constructed directly must never fall through to a decode
            # with no key.
            raise ServiceUnavailableError("Authentication is not configured on this service.")

        if not token or not isinstance(token, str):
            raise UnauthorizedError("Authentication required.")

        claims = self._decode(token)
        context = self._token_context(claims)
        return await self._resolve_identity(context)

    # ── stage 1: cryptography ───────────────────────────────────────────────

    def _reject_unpinned_algorithm(self, token: str) -> None:
        """Refuse a token whose declared algorithm is not pinned, before any I/O.

        Reading the *unverified* header is safe precisely because nothing here
        trusts it: this is a rejection filter, not an algorithm selection. Doing
        it first means `alg: none` and an HMAC forgery are answered 401 without
        a JWKS round-trip, instead of surfacing as "no signing key matches this
        token" — which would be a 503, and would make a plainly invalid token
        look like an outage on the auth service.
        """
        import jwt
        from jwt import PyJWTError

        try:
            header = jwt.get_unverified_header(token)
        except PyJWTError as exc:
            raise UnauthorizedError("Authentication required.") from exc
        algorithm = str(header.get("alg") or "").upper()
        if algorithm not in self._algorithms:
            # The rejected value is attacker-controlled, so it is deliberately
            # not echoed into the log — only the fact that it did not match.
            logger.info(
                "auth_token_algorithm_rejected",
                extra={"event": "auth_token_algorithm_rejected", "provider": "neon"},
            )
            raise UnauthorizedError("Authentication required.")

    def _decode(self, token: str) -> dict[str, Any]:
        import jwt
        from jwt import PyJWTError

        self._reject_unpinned_algorithm(token)

        settings = self._settings
        options = {
            "verify_signature": True,
            "verify_exp": True,
            "verify_nbf": True,
            "verify_iat": True,
            # `aud` is only enforced when configured: observed tokens carry it,
            # but PyJWT rejects a token with no `aud` when an expectation is
            # set, and a guaranteed 401 for everyone is worse than the
            # defence-in-depth. See the `neon_auth_jwt_audience` field.
            "verify_aud": bool(settings.neon_auth_jwt_audience),
            "verify_iss": bool(settings.neon_auth_jwt_issuer),
            # A JWT with no subject cannot identify a user; refuse it rather
            # than produce a context with an empty id.
            "require": ["exp", "sub"],
        }
        decode_kwargs: dict[str, Any] = {
            "algorithms": list(self._algorithms),
            "options": options,
            "leeway": settings.jwt_leeway_seconds,
        }
        if settings.neon_auth_jwt_audience:
            decode_kwargs["audience"] = settings.neon_auth_jwt_audience
        if settings.neon_auth_jwt_issuer:
            decode_kwargs["issuer"] = settings.neon_auth_jwt_issuer

        try:
            signing_key = self._jwks_signing_key(token)
            return jwt.decode(token, signing_key, **decode_kwargs)
        except ServiceUnavailableError:
            raise
        except PyJWTError as exc:
            # Type only — never the message. PyJWT's text can echo claim values,
            # and one generic client-side message for every failure mode keeps
            # this endpoint from becoming an oracle for iterating on a forgery.
            logger.info(
                "auth_token_rejected",
                extra={
                    "event": "auth_token_rejected",
                    "provider": "neon",
                    "error_type": type(exc).__name__,
                },
            )
            raise UnauthorizedError("Authentication required.") from exc

    def _jwks_signing_key(self, token: str) -> Any:
        if self._jwks_client is None:
            from jwt import PyJWKClient

            url = self._settings.neon_auth_jwks_url
            if not url:
                # Unreachable by construction: `neon_jwt_verification_mode` only
                # reports "jwks" when a URL is present. Checked rather than
                # asserted because under `python -O` an assert disappears and
                # the alternative is an AttributeError inside token
                # verification — which must fail closed and loud, not open.
                raise ServiceUnavailableError(
                    "Token verification is misconfigured on this server.",
                    details={"reason": "NEON_AUTH_JWKS_URL is not set."},
                )
            # PyJWKClient caches the document in-process and refetches on an
            # unknown `kid` or once `lifespan` elapses, which matches the
            # service's key rotation. `lifespan=300` bounds how long a
            # rotated-out key stays usable; `timeout` bounds how long a hung
            # JWKS endpoint can stall a request.
            self._jwks_client = PyJWKClient(
                url, cache_keys=True, cache_jwk_set=True, lifespan=300, timeout=10
            )
        try:
            return self._jwks_client.get_signing_key_from_jwt(token)
        except Exception as exc:
            if not self._jwks_checked:
                logger.warning(
                    "auth_jwks_fetch_failed",
                    extra={
                        "event": "auth_jwks_fetch_failed",
                        "provider": "neon",
                        "error_type": type(exc).__name__,
                    },
                )
                self._jwks_checked = True
            raise ServiceUnavailableError(
                "Authentication is temporarily unavailable. Please try again shortly."
            ) from exc

    def _token_context(self, claims: dict[str, Any]) -> AuthContext:
        """Claims → an *authenticated but unauthorized* context.

        `subject` stays `None` here on purpose: nothing in a Neon Auth token can
        supply MaliHub's application user id, and defaulting it to `sub` would
        reproduce the exact conflation this migration exists to remove.
        """
        auth_user_id = claims.get("sub")
        if not isinstance(auth_user_id, str) or not auth_user_id:
            raise UnauthorizedError("Authentication required.")

        # The `role` claim is read for exactly one thing: nothing. It is the
        # Postgres/RLS role ("authenticated"), not an application role, and no
        # branch below may consult it. `claims` is still stored verbatim for the
        # rare handler that needs an unmodelled value.
        email = claims.get("email")
        return AuthContext(
            auth_user_id=auth_user_id,
            subject=None,
            email=email.lower() if isinstance(email, str) else None,
            phone=None,
            email_confirmed=bool(claims.get("email_verified") or claims.get("emailVerified")),
            token_id=claims.get("jti") if isinstance(claims.get("jti"), str) else None,
            issued_at=_as_int(claims.get("iat")),
            expires_at=_as_int(claims.get("exp")),
            claims=claims,
        )

    # ── stage 2: authorization from Postgres ────────────────────────────────

    async def _resolve_identity(self, context: AuthContext) -> AuthContext:
        resolver = self._resolver if self._resolver is not None else get_identity_resolver()
        identity: ApplicationIdentity | None = await resolver.resolve(context.auth_user_id)

        if identity is None:
            # Authenticated by the provider, unknown to MaliHub. 403 rather than
            # 401: we do know who they are, they just have no account here yet.
            logger.warning(
                "auth_identity_unmapped",
                extra={
                    "event": "auth_identity_unmapped",
                    "detail": "A valid provider token presented an id with no users.auth_user_id mapping.",
                },
            )
            raise ForbiddenError("This account isn't linked to a MaliHub profile.")

        if not identity.may_act:
            # Banned or deactivated. Read per request, so this takes effect
            # immediately instead of at token expiry. Deliberately does not say
            # which of the two it was.
            logger.warning(
                "auth_account_disabled",
                extra={
                    "event": "auth_account_disabled",
                    "banned": identity.is_banned,
                    "active": identity.is_active,
                },
            )
            raise ForbiddenError("This account can't be used to access the API.")

        # Postgres is authoritative for everything it knows. The token's email
        # is kept only as a fallback for a row where the column is somehow
        # empty, never as an override.
        return replace(
            context,
            subject=identity.user_id,
            role=identity.role,
            is_onboarded=identity.is_onboarded,
            has_seller_profile=identity.has_seller_profile,
            email=identity.email or context.email,
            phone=identity.phone,
            email_confirmed=identity.email_verified,
            is_banned=identity.is_banned,
            is_active=identity.is_active,
        )


# ─── Factory & FastAPI wiring ────────────────────────────────────────────────

_verifier: TokenVerifier | None = None


def get_token_verifier(settings: Settings | None = None) -> TokenVerifier:
    """Process-wide verifier, chosen by `auth_provider`.

    Returns `UnconfiguredVerifier` (fail-closed) when the *selected* provider
    cannot verify tokens, so a missing env var can never degrade into "everyone
    is anonymous but allowed".

    There is deliberately **no cross-provider fallback**. If
    `AUTH_PROVIDER=neon` and Neon is unconfigured, this does not quietly accept
    Supabase tokens because a secret happens to be set: that would leave a stale
    trust root alive after the cutover, which is the one property the migration
    most needs to guarantee. Rolling back means setting
    `AUTH_PROVIDER=supabase-legacy` explicitly.
    """
    global _verifier
    if _verifier is None:
        resolved = settings or get_settings()
        candidate: TokenVerifier = (
            NeonAuthJwtVerifier(resolved)
            if resolved.auth_provider == "neon"
            else SupabaseJwtVerifier(resolved)
        )
        if candidate.is_configured:
            _verifier = candidate
        else:
            _verifier = UnconfiguredVerifier(resolved)
            logger.warning(
                "auth_verifier_unconfigured",
                extra={
                    "event": "auth_verifier_unconfigured",
                    "provider": resolved.auth_provider,
                    "detail": resolved.describe_missing_auth_configuration(),
                },
            )
    return _verifier


def reset_token_verifier() -> None:
    """Drop the cached verifier. For tests that change settings between cases."""
    global _verifier
    _verifier = None


def extract_bearer_token(request: Request) -> str | None:
    """Pull the token out of `Authorization: Bearer <jwt>`.

    Case-insensitive scheme match (RFC 7235 says the scheme is case-insensitive,
    and clients get this wrong constantly). Anything else — a cookie, a query
    param, a custom header — is not accepted: query-param tokens end up in
    proxy and access logs, and accepting cookies here would make this API
    subject to CSRF, which `src/lib/csrf.ts` exists to prevent on the frontend.
    """
    header = request.headers.get("authorization")
    if not header:
        return None
    scheme, _, credentials = header.partition(" ")
    if scheme.lower() != "bearer":
        return None
    token = credentials.strip()
    return token or None


async def get_auth_context(request: Request) -> AuthContext:
    """Dependency: require a valid Supabase token. 401 if absent or invalid.

    @router.get("/me")
    async def me(user: AuthContext = Depends(get_auth_context)): ...
    """
    token = extract_bearer_token(request)
    if token is None:
        logger.info(
            "auth_missing_token",
            extra={
                "event": "auth_missing_token",
                "path": request.url.path,
                "has_authorization_header": "authorization" in request.headers,
            },
        )
        raise UnauthorizedError("Authentication required.")
    return await get_token_verifier().verify(token)


async def get_optional_auth_context(request: Request) -> AuthContext | None:
    """Dependency: identify the caller if they presented a token, else None.

    For endpoints that work either way but personalize when they can. A
    *malformed* token still 401s rather than silently becoming anonymous — a
    client that thinks it is authenticated should be told it isn't, not served
    the logged-out view of its own data.
    """
    token = extract_bearer_token(request)
    if token is None:
        return None
    return await get_token_verifier().verify(token)


def require_role(*roles: str) -> Any:
    """Dependency factory gating an endpoint to specific application roles.

        @router.post("/admin/things")
        async def create(user: AuthContext = Depends(require_role("ADMIN", "SUPER_ADMIN"))): ...

    Role names are uppercased and validated against `APP_ROLES` at *definition*
    time, so a typo in a decorator fails on import instead of silently
    permitting nobody (or, with a looser check, everybody).

    This is a coarse gate, not the authorization boundary. The Next.js
    `middleware.ts` role check is likewise a fast path — anything
    security-sensitive must still re-verify ownership against Postgres in the
    service layer, exactly as the existing Server Actions do.
    """
    normalized: tuple[str, ...] = tuple(role.upper() for role in roles)
    unknown = [role for role in normalized if role not in APP_ROLES]
    if unknown:
        raise ValueError(f"require_role() got unknown application role(s): {unknown}")
    if not normalized:
        raise ValueError("require_role() needs at least one role.")

    allowed: frozenset[str] = frozenset(normalized)

    async def dependency(user: AuthContext = Depends(get_auth_context)) -> AuthContext:
        if user.role not in allowed:
            # Deliberately does not say which role was required: that tells a
            # caller what to aim for.
            logger.warning(
                "auth_role_denied",
                extra={
                    "event": "auth_role_denied",
                    "role": user.role,
                    "required_count": len(allowed),
                },
            )
            raise ForbiddenError("You don't have permission to do that.")
        return user

    return dependency


def seconds_until_expiry(context: AuthContext, *, skew: int = 30) -> int:
    """Seconds until a token expires, floored at 0. For cache TTLs.

    Never cache anything derived from a request longer than the token that
    authorized it, or a cached value outlives the permission to see it.
    """
    if context.expires_at is None:
        return 0
    return max(0, int(context.expires_at - time.time() - skew))


def allowed_roles_for(roles: Iterable[str]) -> tuple[str, ...]:
    """Validate/normalize a role list. Exposed for schema-level validation."""
    normalized = tuple(role.upper() for role in roles)
    unknown = [role for role in normalized if role not in APP_ROLES]
    if unknown:
        raise ValueError(f"Unknown application role(s): {unknown}")
    return normalized
